apiVersion: batch/v1
kind: Job
metadata:
  name: task-migration-job
spec:
  template:
    metadata:
      name: migrate
      labels:
        app: devops-project
        tier: migration
        name: migrate
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: [ "sh", "-c", "until pg_isready -h task-db-cluster-ip; do echo waiting; sleep 2; done" ]
      containers:
        - name: devops-project-task-migration
          image: jkole822/devops-project-task-migration
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: tasks-secret