apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis-cluster-ip
spec:
  selector:
    app: {{ .Values.redis.labels.app | default "devops-project" }}
    tier: {{ .Values.redis.labels.tier | default "cache-queue" }}
    name: {{ .Values.redis.labels.name | default "redis" }}
  ports:
    - targetPort: {{ .Values.redis.ports.containerPort | default 6379 }}
      port: {{ .Values.redis.ports.containerPort | default 6379 }}