apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
      tier: database
      name: task_db
  template:
    metadata:
      name: task_db
      labels:
        app: devops-project
        tier: database
        name: task_db
    spec:
      containers:
        - name: devops-project-task-db
          image: postgres:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tasks-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tasks-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tasks-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: task-pvc