apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-cluster-ip
spec:
  selector:
    app: {{ .Values.labels.app | default "devops-project" }}
    tier: {{ .Values.labels.tier | default "backend" }}
    name: {{ .Values.labels.name | default "task_api" }}
  ports:
    - targetPort: {{ .Values.ports.containerPort | default 8000 }}
      port: {{ .Values.ports.containerPort | default 8000 }}