apiVersion: v1
kind: Pod
metadata:
  name: auth_db
  labels:
    app: devops-project
    tier: database
    name: auth_db
spec:
  containers:
    - name: devops-project-auth-db
      image: postgres:15
      envFrom:
        - secretRef:
            name: auth-secret
