apiVersion: v1
kind: Pod
metadata:
  name: migrate
  labels:
    app: devops-project
    tier: migration
    name: migrate
spec:
  containers:
    - name: devops-project-task-migration
      image: jkole822/devops-project-task-migration
      envFrom:
        - secretRef:
            name: tasks-secret