apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app: {{ .Values.labels.app | default "devops-project" }}
    tier: {{ .Values.labels.tier | default "frontend" }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.paths.frontend.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.paths.frontend.serviceName | default "frontend-cluster-ip" }}
                port:
                  number: {{ .Values.ingress.paths.frontend.port | default 80 }}
          - path: {{ .Values.ingress.paths.auth.path | default "/auth" }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.ingress.paths.auth.serviceName | default "auth-api-cluster-ip" }}
                port:
                  number: {{ .Values.ingress.paths.auth.port | default 8080 }}
          - path: {{ .Values.ingress.paths.auth.loginPath | default "/login" }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.ingress.paths.auth.serviceName | default "auth-api-cluster-ip" }}
                port:
                  number: {{ .Values.ingress.paths.auth.port | default 8080 }}
          - path: {{ .Values.ingress.paths.task.path | default "/task" }}
            pathType: {{ .Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .Values.ingress.paths.task.serviceName | default "task-api-cluster-ip" }}
                port:
                  number: {{ .Values.ingress.paths.task.port | default 8000 }}