apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db-cluster-ip
spec:
  selector:
    app: {{ .Values.db.labels.app | default "devops-project" }}
    tier: {{ .Values.db.labels.tier | default "database" }}
    name: {{ .Values.db.labels.name | default "auth_db" }}
  ports:
    - targetPort: {{ .Values.db.ports.containerPort | default 5432 }}
      port: {{ .Values.db.ports.containerPort | default 5432 }}