apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.labels.app | default "devops-project" }}
      tier: {{ .Values.db.labels.tier | default "database" }}
      name: {{ .Values.db.labels.name | default "auth_db" }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.labels.app | default "devops-project" }}
        tier: {{ .Values.db.labels.tier | default "database" }}
        name: {{ .Values.db.labels.name | default "auth_db" }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: {{ .Values.db.image | default "postgres:15" }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: {{ .Values.volumes.name | default "postgres-data" }}
              mountPath: {{ .Values.volumes.mountPath | default "/var/lib/postgresql/data" }}
      volumes:
        - name: {{ .Values.volumes.name | default "postgres-data" }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc