replicaCount: 1
image:
  repository: jkole822/devops-project-app
  tag: latest
labels:
  app: devops-project
  tier: frontend
  name: app
ports:
  containerPort: 80
  nodePort: 30002
ingress:
  enabled: true
  paths:
    frontend:
      path: /
      serviceName: frontend-cluster-ip
      port: 80
    auth:
      path: /auth
      loginPath: /login
      serviceName: auth-api-cluster-ip
      port: 8080
    task:
      path: /task
      serviceName: task-api-cluster-ip
      port: 8000
  pathType: Prefix

